tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': 'var(--color-on-surface)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary': 'var(--color-on-primary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        secondary: 'var(--color-secondary)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'status-active': 'var(--color-status-active)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'tag-teach-bg': 'var(--color-tag-teach-bg)',
        'surface-tint': 'var(--color-surface-tint)',
        'status-completed': 'var(--color-status-completed)',
        background: 'var(--color-background)',
        'error-container': 'var(--color-error-container)',
        surface: 'var(--color-surface)',
        'status-active-bg': 'var(--color-status-active-bg)',
        'on-error': 'var(--color-on-error)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-error-container': 'var(--color-on-error-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'primary-container': 'var(--color-primary-container)',
        'tag-learn-border': 'var(--color-tag-learn-border)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'tag-learn-text': 'var(--color-tag-learn-text)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'surface-variant': 'var(--color-surface-variant)',
        'tag-teach-border': 'var(--color-tag-teach-border)',
        'surface-container': 'var(--color-surface-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        outline: 'var(--color-outline)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'status-pending': 'var(--color-status-pending)',
        primary: 'var(--color-primary)',
        'tag-learn-bg': 'var(--color-tag-learn-bg)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'status-completed-bg': 'var(--color-status-completed-bg)',
        'status-pending-bg': 'var(--color-status-pending-bg)',
        error: 'var(--color-error)',
        'on-secondary': 'var(--color-on-secondary)',
        'tag-teach-text': 'var(--color-tag-teach-text)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2xl': '4rem',
        margin: '2rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'margin-mobile': '1.25rem',
        'gutter-mobile': '1rem',
        'space-lg': '1.5rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-hero': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-hero-mobile': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'headline-hero-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.025em', fontWeight: '800' }],
      },
    },
  },
};
