tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1c1a',
        'primary-fixed': '#ffdbd1',
        'secondary-container': '#e4e1e5',
        'on-primary': '#ffffff',
        'inverse-primary': '#ffb59f',
        'outline-variant': '#dfc0b7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        secondary: '#5f5e61',
        'inverse-on-surface': '#f2f0ed',
        'on-surface-variant': '#58423b',
        'status-active': '#246b43',
        'surface-dim': '#dbdad6',
        'on-tertiary-fixed': '#1d1c14',
        'surface-container-high': '#eae8e4',
        'secondary-fixed-dim': '#c8c6c9',
        'tag-teach-bg': '#ffdbd1',
        'surface-tint': '#a83813',
        'status-completed': '#545249',
        background: '#fbf9f5',
        'error-container': '#ffdad6',
        surface: '#fbf9f5',
        'status-active-bg': '#e4f5ea',
        'on-error': '#ffffff',
        'tertiary-container': '#6d6a61',
        'secondary-fixed': '#e4e1e6',
        'on-tertiary-container': '#c9c5ba',
        tertiary: '#3d3b33',
        'on-secondary-fixed': '#1b1b1e',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#49473e',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fbf9f5',
        'on-secondary-container': '#656467',
        'on-primary-fixed': '#3a0a00',
        'on-secondary-fixed-variant': '#47464a',
        'on-background': '#1b1c1a',
        'primary-container': '#b8431e',
        'tag-learn-border': '#c8c5ca',
        'surface-container-highest': '#e4e2de',
        'tag-learn-text': '#47464a',
        'tertiary-fixed': '#e7e2d6',
        'surface-variant': '#e4e2de',
        'tag-teach-border': '#dfc0b7',
        'surface-container': '#efeeea',
        'tertiary-fixed-dim': '#cbc6bc',
        outline: '#8c716a',
        'inverse-surface': '#30312e',
        'status-pending': '#9c6000',
        primary: '#711c00',
        'tag-learn-bg': '#e4e1e6',
        'on-primary-fixed-variant': '#862300',
        'primary-fixed-dim': '#ffb59f',
        'on-primary-container': '#ffe5de',
        'status-completed-bg': '#e7e2d7',
        'status-pending-bg': '#fef3d6',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'tag-teach-text': '#862200',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2xl': '4rem',
        margin: '2rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'margin-mobile': '1.25rem',
        'gutter-mobile': '1rem',
        'space-lg': '1.5rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-hero': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-hero-mobile': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'headline-hero-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.025em', fontWeight: '800' }],
      },
    },
  },
};
